[package]
name = "common"
version = "0.1.0"
edition = "2021"

[dependencies]
entity = { path = "../database/entity" }
serde = { version = "1.0.152", features = ["derive"] }
uuid = { version = "1.3.0", features = ["serde"] }
url = { version = "2.3.1", features = ["serde"] }
ron = "0.8.0"
